// База данных Heroes of the Storm
window.heroesData = {
    // Список всех героев
    heroes: [
        "Abathur", "Anub'arak", "Arthas", "Blaze", "Cho", "Diablo", "E.T.C.", "Garrosh", "Johanna", "Mal'Ganis",
        "Medivh", "Muradin", "Stitches", "Tyrael", "Artanis", "Chen", "D.Va", "Dehaka", "Imperius", "Leoric",
        "Malthael", "Ragnaros", "Rexxar", "Sonya", "Thrall", "The Lost Vikings", "Varian", "Xul", "Yrel", "Zarya",
        "Azmodan", "Gazlowe", "Hogger", "Mei", "Cassia", "Chromie", "Falstad", "Fenix", "Gall", "Genji",
        "Greymane", "Gul'dan", "Hanzo", "Jaina", "Junkrat", "Kael'thas", "Kel'Thuzad", "Li-Ming", "Lunara", "Mephisto",
        "Nazeebo", "Nova", "Orphea", "Probius", "Raynor", "Sgt. Hammer", "Sylvanas", "Tassadar", "Tracer", "Tychus",
        "Valla", "Zagara", "Zul'jin", "Alarak", "Illidan", "Kerrigan", "Maiev", "Murky", "Qhira", "Samuro",
        "The Butcher", "Valeera", "Zeratul", "Alexstrasza", "Ana", "Anduin", "Auriel", "Brightwing", "Deckard Cain",
        "Kharazim", "Li Li", "Lt. Morales", "Lúcio", "Malfurion", "Rehgar", "Stukov", "Tyrande", "Uther", "Whitemane"
    ],

    // Список всех карт
    maps: [
        "Alterac Pass", "Battlefield of Eternity", "Blackheart's Bay", "Braxis Holdout", "Cursed Hollow", 
        "Dragon Shire", "Garden of Terror", "Hanamura Temple", "Infernal Shrines", "Sky Temple", 
        "Tomb of the Spider Queen", "Towers of Doom", "Volskaya Foundry", "Warhead Junction"
    ],

    // Категории героев
    heroCategories: {
        tanks: [
            "Anub'arak", "Arthas", "Blaze", "Cho", "Diablo", "E.T.C.", "Garrosh", "Johanna", "Mal'Ganis",
            "Muradin", "Stitches", "Tyrael", "Artanis", "Chen", "D.Va", "Dehaka", "Imperius", "Leoric",
            "Malthael", "Ragnaros", "Rexxar", "Sonya", "Thrall", "Varian", "Yrel", "Zarya"
        ],
        healers: [
            "Alexstrasza", "Ana", "Anduin", "Auriel", "Brightwing", "Deckard Cain", "Kharazim", "Li Li",
            "Lt. Morales", "Lúcio", "Malfurion", "Rehgar", "Stukov", "Tyrande", "Uther", "Whitemane"
        ],
        damage: [
            "Abathur", "Alarak", "Azmodan", "Cassia", "Chromie", "Falstad", "Fenix", "Gall", "Genji",
            "Greymane", "Gul'dan", "Hanzo", "Illidan", "Jaina", "Junkrat", "Kael'thas", "Kel'Thuzad",
            "Kerrigan", "Li-Ming", "Lunara", "Maiev", "Mephisto", "Nova", "Orphea", "Raynor",
            "Sgt. Hammer", "Sylvanas", "Tassadar", "Tracer", "Tychus", "Valla", "Zul'jin"
        ],
        specialists: [
            "Gazlowe", "Hogger", "Mei", "Murky", "Nazeebo", "Probius", "Qhira", "Samuro",
            "The Butcher", "The Lost Vikings", "Valeera", "Zagara", "Zeratul", "Xul"
        ]
    },

    // Синергии героев
    synergies: {
        "Abathur": ["Illidan", "Zeratul", "Tracer", "Greymane", "Genji", "Malthael", "Yrel", "Sonya"],
        "Anub'arak": ["Greymane", "Jaina", "Kael'thas", "Kerrigan", "Rehgar", "The Butcher"],
        "Arthas": ["Diablo", "Tyrael", "Maiev", "Greymane", "Raynor", "Chromie", "Zarya", "Stukov", "Rehgar"],
        "Blaze": ["Arthas", "Kerrigan", "Maiev", "Malfurion"],
        "Cho": ["Alexstrasza", "Ana", "Auriel", "Brightwing", "Yrel", "Blaze"],
        "Diablo": ["Thrall", "Tassadar", "Medivh", "Tyrande", "Leoric", "Valla"],
        "E.T.C.": ["Blaze", "Alarak", "Greymane", "Kael'thas", "Uther"],
        "Garrosh": ["Hanzo", "Jaina", "Zarya", "Malfurion"],
        "Johanna": ["Blaze", "Maiev", "Hanzo", "Jaina", "Deckard Cain"],
        "Mal'Ganis": ["Jaina", "Zeratul", "Malfurion"],
        "Muradin": ["Blaze", "Kerrigan", "Kael'thas", "Hanzo", "Malfurion"],
        "Stitches": ["Blaze", "Falstad", "Kael'thas", "Malfurion"],
        "Tyrael": ["Blaze", "Illidan", "Malfurion"],
        "Artanis": ["Garrosh", "Arthas", "Kael'thas", "Lunara", "Medivh", "Malfurion"],
        "Chen": ["Tyrael", "Greymane", "Li-Ming", "Abathur", "Rehgar"],
        "D.Va": ["Garrosh", "Maiev", "Falstad", "Deckard Cain"],
        "Dehaka": ["Anub'arak", "Jaina", "Hanzo", "Maiev"],
        "Imperius": ["Jaina", "Fenix", "Rehgar", "Mal'Ganis", "E.T.C.", "Yrel", "Blaze"],
        "Leoric": ["Diablo", "Orphea", "Stukov", "Valla", "Tassadar"],
        "Malthael": ["E.T.C.", "Garrosh", "Greymane", "Tychus", "Medivh", "Ana", "Malfurion"],
        "Ragnaros": ["E.T.C.", "Hanzo", "Kael'thas", "Ana"],
        "Rexxar": ["Johanna", "Jaina", "Malfurion"],
        "Sonya": ["Jaina", "Medivh", "Rehgar", "Zarya"],
        "Thrall": ["Diablo", "Fenix", "Chromie", "Rehgar"],
        "The Lost Vikings": ["Zarya", "Garrosh", "Sylvanas", "Raynor", "Sgt. Hammer"],
        "Varian": ["E.T.C.", "Blaze", "Li-Ming", "Tyrande"],
        "Xul": ["Tyrande", "Medivh", "Li-Ming", "Falstad"],
        "Yrel": ["Garrosh", "Johanna", "Maiev", "Abathur"],
        "Zarya": ["Garrosh", "Sonya", "Malfurion", "Valla"],
        "Azmodan": ["Jaina", "Johanna", "Maiev", "Malfurion"],
        "Gazlowe": ["Diablo", "E.T.C.", "Jaina", "Johanna", "Kael'thas", "Malfurion"],
        "Hogger": ["Diablo", "Sonya", "Hanzo", "Li-Ming", "Stukov"],
        "Mei": ["Xul", "Lunara", "Jaina", "Deckard Cain"],
        "Cassia": ["Li Li", "Johanna", "Artanis", "Thrall", "Jaina"],
        "Chromie": ["Johanna", "Ana", "Malfurion"],
        "Falstad": ["Arthas", "E.T.C.", "Tassadar", "Uther"],
        "Fenix": ["Johanna", "Maiev", "Thrall", "Diablo"],
        "Gall": ["Alexstrasza", "Ana", "Auriel", "Brightwing", "Yrel", "Blaze"],
        "Genji": ["Jaina", "Uther", "E.T.C.", "Garrosh", "Anub'arak"],
        "Greymane": ["Abathur", "E.T.C.", "Garrosh", "Tyrael", "Uther", "Rehgar", "Malthael"],
        "Gul'dan": ["E.T.C.", "Malfurion", "Auriel"],
        "Hanzo": ["Zeratul", "E.T.C.", "Diablo", "Blaze", "Johanna", "Mal'Ganis"],
        "Jaina": ["E.T.C.", "Johanna", "Maiev", "Malfurion", "Muradin", "Varian", "Xul"],
        "Junkrat": ["E.T.C.", "Garrosh", "Uther", "Malfurion", "Zeratul"],
        "Kael'thas": ["E.T.C.", "Arthas", "Malfurion", "Uther"],
        "Kel'Thuzad": ["Anduin", "Arthas", "Johanna", "Malfurion", "The Butcher", "Valeera", "Varian", "Xul"],
        "Li-Ming": ["Arthas", "E.T.C.", "Johanna", "Malfurion", "Valeera", "Varian", "Xul"],
        "Lunara": ["Arthas", "Muradin", "Jaina"],
        "Mephisto": ["Deckard Cain", "E.T.C.", "Zarya", "Diablo"],
        "Nazeebo": ["Johanna", "Raynor", "Stukov"],
        "Nova": ["Johanna", "Blaze", "Sylvanas", "Stukov"],
        "Orphea": ["Anub'arak", "Chen", "Genji", "Johanna", "Lunara", "Muradin"],
        "Probius": ["Kerrigan", "Alarak", "Zeratul", "Tracer"],
        "Raynor": ["E.T.C.", "Garrosh", "Thrall", "Lt. Morales"],
        "Sgt. Hammer": ["E.T.C.", "Johanna", "Lt. Morales", "Ana"],
        "Sylvanas": ["Diablo", "E.T.C.", "Jaina", "Tassadar", "Tyrande", "Valla"],
        "Tassadar": ["Maiev", "Johanna", "E.T.C.", "Genji", "Zeratul", "Valla"],
        "Tracer": ["Tassadar", "Jaina", "Gul'dan", "Kael'thas", "Malfurion", "Anduin", "Abathur"],
        "Tychus": ["Garrosh", "E.T.C.", "Dehaka", "Uther"],
        "Valla": ["Arthas", "Garrosh", "Auriel", "Uther", "Diablo", "Leoric", "Tassadar"],
        "Zagara": ["E.T.C.", "Jaina", "Deckard Cain"],
        "Zul'jin": ["Tyrael", "E.T.C.", "Tassadar", "Uther", "Medivh", "Arthas"],
        "Alarak": ["Raynor", "Jaina", "E.T.C.", "Garrosh"],
        "Illidan": ["Abathur", "Medivh", "Rehgar", "Tyrael", "Uther", "Zarya"],
        "Kerrigan": ["Tyrael", "Uther", "Medivh", "Auriel", "Lúcio"],
        "Maiev": ["E.T.C.", "Blaze", "Jaina", "Tassadar", "Deckard Cain", "Malfurion"],
        "Medivh": ["Illidan", "Greymane", "Genji", "Tracer", "Diablo", "Stitches"],
        "Murky": ["Johanna", "Zarya", "Brightwing"],
        "Qhira": ["Uther", "Rehgar", "Abathur", "Anub'arak"],
        "Samuro": ["Abathur", "Deckard Cain", "Malfurion", "Sylvanas"],
        "The Butcher": ["Abathur", "Tyrande", "Uther", "Tyrael"],
        "Valeera": ["Garrosh", "E.T.C.", "Abathur"],
        "Zeratul": ["Brightwing", "Uther", "Varian", "Diablo", "E.T.C.", "Medivh"],
        "Alexstrasza": ["Johanna", "Kael'thas", "Blaze", "Azmodan"],
        "Ana": ["Lúcio", "Zeratul", "Hanzo", "Anub'arak"],
        "Anduin": ["Johanna", "Blaze", "The Butcher", "Alarak", "Genji", "Sylvanas"],
        "Auriel": ["Diablo", "Leoric", "Valla", "Tassadar"],
        "Brightwing": ["Diablo", "Stitches", "Cho", "Tracer", "Genji"],
        "Deckard Cain": ["Johanna", "Blaze", "Sgt. Hammer", "Jaina"],
        "Kharazim": ["Garrosh", "Genji", "Anub'arak", "E.T.C."],
        "Li Li": ["Johanna", "Blaze", "Hanzo", "Kael'thas", "Uther"],
        "Lt. Morales": ["Johanna", "Raynor"],
        "Lúcio": ["Arthas", "Diablo", "Greymane", "Valla"],
        "Malfurion": ["Blaze", "Chromie", "Gul'dan", "Jaina", "Kael'thas", "Kel'Thuzad", "Li-Ming", "Nazeebo", "Ragnaros"],
        "Rehgar": ["Valla", "Illidan", "Greymane"],
        "Stukov": ["Raynor", "E.T.C.", "Sgt. Hammer"],
        "Tyrande": ["Diablo", "E.T.C.", "Varian", "Anub'arak", "Li-Ming"],
        "Uther": ["E.T.C.", "Kerrigan", "Illidan", "The Butcher", "Zul'jin", "Malfurion"],
        "Whitemane": ["Johanna", "Sonya", "Chromie", "Hanzo"]
    },

    // Контры героев
    counteredBy: {
        "Abathur": ["Dehaka", "Falstad", "Ragnaros", "Zarya", "Sylvanas", "Sgt. Hammer"],
        "Anub'arak": ["Leoric", "Malthael", "Tracer", "Valla", "Varian", "Zul'jin"],
        "Arthas": ["Garrosh", "Sonya", "Tracer", "Raynor", "Jaina", "Ana"],
        "Blaze": ["Leoric", "Lunara", "Malthael", "Nova", "Tracer", "Valla"],
        "Cho": ["Anub'arak", "Garrosh", "Greymane", "Imperius", "Kharazim", "Leoric", "Maiev", "Malthael", "Raynor"],
        "Diablo": ["Garrosh", "Leoric", "Malthael", "Raynor", "Tychus"],
        "E.T.C.": ["Johanna", "Deathwing", "Raynor", "Kael'thas", "Brightwing"],
        "Garrosh": ["Johanna", "Malthael", "Hanzo", "Jaina", "Anduin"],
        "Johanna": ["Varian", "Leoric", "Hanzo", "Zeratul"],
        "Mal'Ganis": ["Jaina", "Zeratul", "Malfurion"],
        "Medivh": ["Gul'dan", "Lunara", "Garrosh", "Malfurion"],
        "Muradin": ["E.T.C.", "Thrall", "Raynor", "Jaina", "Malfurion"],
        "Stitches": ["Johanna", "Malthael", "Greymane", "Tychus", "Anduin"],
        "Tyrael": ["Garrosh", "E.T.C.", "Zeratul", "Greymane"],
        "Artanis": ["E.T.C.", "Arthas", "Varian", "Jaina", "Lunara", "Li Li"],
        "Chen": ["E.T.C.", "Yrel", "Raynor", "Li-Ming", "The Lost Vikings", "Lúcio"],
        "D.Va": ["E.T.C.", "Malthael", "Raynor", "Kael'thas", "Stukov"],
        "Dehaka": ["Valla", "Raynor", "E.T.C.", "Sgt. Hammer", "Lúcio"],
        "Imperius": ["Jaina", "Raynor", "Sgt. Hammer", "Zul'jin", "E.T.C.", "Yrel", "Blaze"],
        "Leoric": ["Dehaka", "Samuro", "Tracer", "Falstad", "Ana"],
        "Malthael": ["Blaze", "Falstad", "Fenix", "Lunara", "Tracer", "Valla"],
        "Ragnaros": ["Garrosh", "Chen", "Lunara", "Jaina", "Stukov"],
        "Rexxar": ["Tyrael", "Illidan", "Qhira", "Zeratul", "Kharazim"],
        "Sonya": ["Brightwing", "E.T.C.", "Muradin", "Diablo", "Garrosh", "Sylvanas", "Tychus"],
        "Thrall": ["Johanna", "Arthas", "Kael'thas", "Lunara", "Malfurion"],
        "The Lost Vikings": ["Zagara", "Sonya", "Zeratul", "Nova", "Falstad", "Dehaka", "Li-Ming", "The Butcher"],
        "Varian": ["E.T.C.", "Arthas", "Lunara", "Medivh", "Rehgar", "Hanzo", "Garrosh", "Uther"],
        "Xul": ["E.T.C.", "Johanna", "Jaina", "Sgt. Hammer", "Auriel"],
        "Yrel": ["E.T.C.", "Lúcio", "Johanna"],
        "Zarya": ["Garrosh", "Yrel", "Lunara", "Maiev", "Auriel"],
        "Azmodan": ["Artanis", "Anub'arak", "Diablo", "Leoric", "Malthael", "Muradin", "Sonya", "The Butcher"],
        "Gazlowe": ["Raynor", "Lunara", "Gul'dan", "Chromie", "Hanzo", "Li-Ming"],
        "Hogger": ["Diablo", "Sonya", "Hanzo", "Li-Ming", "Stukov"],
        "Mei": ["Xul", "Lunara", "Jaina", "Deckard Cain"],
        "Cassia": ["Li Li", "Johanna", "Artanis", "Thrall", "Jaina"],
        "Chromie": ["Illidan", "Diablo", "Zeratul", "Tracer"],
        "Falstad": ["Genji", "Greymane", "Illidan", "Nova", "Valeera", "Zeratul"],
        "Fenix": ["Varian", "E.T.C.", "Genji", "Zeratul", "Lúcio"],
        "Gall": ["Anub'arak", "Garrosh", "Greymane", "Imperius", "Kharazim", "Leoric", "Maiev", "Malthael", "Raynor"],
        "Genji": ["Varian", "Malfurion", "Lunara", "Uther"],
        "Greymane": ["Arthas", "Brightwing", "Johanna", "Muradin", "The Butcher", "Uther", "Xul"],
        "Gul'dan": ["Illidan", "Greymane", "Kerrigan", "Tracer"],
        "Hanzo": ["Genji", "Illidan", "Zeratul"],
        "Jaina": ["Alarak", "Anub'arak", "Chen", "Genji", "Nova", "Tracer", "Valeera", "Zeratul"],
        "Junkrat": ["Illidan", "Tracer", "Zeratul", "Tyrael", "Genji"],
        "Kael'thas": ["Illidan", "Zeratul", "Kerrigan", "Tracer"],
        "Kel'Thuzad": ["Anub'arak", "Chen", "Genji", "Nova", "Samuro", "Tracer", "Valeera", "Zeratul"],
        "Li-Ming": ["Anub'arak", "Chen", "Genji", "Samuro", "Tracer", "Valeera", "Zeratul"],
        "Lunara": ["Illidan", "Genji", "Malfurion", "Stukov"],
        "Mephisto": ["Kael'thas", "Kel'Thuzad", "Junkrat", "Stitches", "Anub'arak"],
        "Nazeebo": ["E.T.C.", "Sylvanas"],
        "Nova": ["Anub'arak", "Chen", "Genji", "Zarya", "Brightwing"],
        "Orphea": ["Anub'arak", "Chen", "Genji", "Johanna", "Lunara", "Muradin"],
        "Probius": ["Kerrigan", "Alarak", "Zeratul", "Tracer"],
        "Raynor": ["Johanna", "Artanis", "Cassia"],
        "Sgt. Hammer": ["Artanis", "Chromie", "Kel'Thuzad", "Li-Ming", "Stitches"],
        "Sylvanas": ["Chen", "Diablo", "Genji", "Nova", "The Butcher", "Valeera", "Zeratul"],
        "Tassadar": ["Tracer", "Greymane", "Zeratul", "Anub'arak", "Kerrigan"],
        "Tracer": ["Varian", "Diablo", "Medivh", "Raynor", "Sgt. Hammer"],
        "Tychus": ["Anub'arak", "Johanna", "Lúcio"],
        "Valla": ["Greymane", "Illidan", "Nova", "The Butcher", "Valeera", "Zeratul"],
        "Zagara": ["Illidan", "Falstad", "Chen", "Zeratul"],
        "Zul'jin": ["E.T.C.", "Dehaka", "Diablo", "Garrosh", "Uther", "Li Li"],
        "Alarak": ["E.T.C.", "Johanna", "Deathwing", "Medivh"],
        "Illidan": ["Arthas", "Brightwing", "E.T.C.", "Li Li", "Johanna", "Muradin", "Sonya", "Uther", "Varian"],
        "Kerrigan": ["Tyrael", "E.T.C.", "Garrosh", "Uther", "Medivh", "Auriel", "Lúcio"],
        "Maiev": ["Arthas", "Tyrael", "E.T.C.", "Johanna", "Lunara", "Tracer", "Lúcio", "Brightwing"],
        "Murky": ["Sonya", "Falstad"],
        "Qhira": ["Lúcio", "Uther", "E.T.C.", "Diablo", "Garrosh", "Tracer"],
        "Samuro": ["Lúcio", "E.T.C.", "Jaina", "Orphea", "Cassia", "Medivh", "Diablo", "Stukov"],
        "The Butcher": ["Johanna", "E.T.C.", "Brightwing", "Uther"],
        "Valeera": ["E.T.C.", "Arthas", "Medivh", "Lúcio"],
        "Zeratul": ["Brightwing", "Uther", "Varian", "Diablo", "E.T.C.", "Medivh"],
        "Alexstrasza": ["Johanna", "Kael'thas", "Blaze", "Azmodan"],
        "Ana": ["Lúcio", "Zeratul", "Hanzo", "Anub'arak"],
        "Anduin": ["Varian", "Sonya", "Lunara", "Kel'Thuzad", "Stukov"],
        "Auriel": ["Anub'arak", "Chen", "Junkrat", "Chromie", "Deckard Cain"],
        "Brightwing": ["Anub'arak", "Johanna", "E.T.C."],
        "Deckard Cain": ["Johanna", "Deathwing", "Tracer", "Li-Ming", "Malfurion"],
        "Kharazim": ["Johanna", "Auriel", "Medivh", "Uther"],
        "Li Li": ["E.T.C.", "Yrel", "Sylvanas", "Jaina", "Stukov"],
        "Lt. Morales": ["Garrosh", "Chen", "Chromie", "Lunara", "Auriel"],
        "Lúcio": ["Deckard Cain", "Malfurion", "Raynor", "Sgt. Hammer"],
        "Malfurion": ["The Butcher", "Auriel", "Ana", "Tyrande", "Lt. Morales"],
        "Rehgar": ["Muradin", "Ana", "Tracer", "Varian"],
        "Stukov": ["Anub'arak", "Genji", "Uther"],
        "Tyrande": ["Anub'arak", "Muradin", "Zeratul", "Maiev", "Fenix", "Lunara"],
        "Uther": ["Gul'dan", "Lunara", "Malthael", "Nazeebo", "Sylvanas", "Zagara"],
        "Whitemane": ["Alarak", "Li-Ming", "Raynor"]
    },

    // Лучшие карты для героев
    bestMaps: {
        "Abathur": ["Alterac Pass", "Cursed Hollow", "Garden of Terror", "Infernal Shrines", "Towers of Doom"],
        "Anub'arak": ["Alterac Pass", "Cursed Hollow", "Dragon Shire", "Garden of Terror"],
        "Arthas": ["Battlefield of Eternity"],
        "Blaze": ["Infernal Shrines", "Sky Temple", "Towers of Doom", "Volskaya Foundry"],
        "Cho": ["Garden of Terror", "Infernal Shrines", "Tomb of the Spider Queen", "Volskaya Foundry"],
        "Diablo": ["Battlefield of Eternity", "Cursed Hollow", "Garden of Terror", "Infernal Shrines", "Tomb of the Spider Queen", "Towers of Doom"],
        "E.T.C.": ["Battlefield of Eternity"],
        "Garrosh": ["Battlefield of Eternity", "Braxis Holdout", "Tomb of the Spider Queen"],
        "Johanna": ["Alterac Pass", "Blackheart's Bay", "Infernal Shrines", "Tomb of the Spider Queen", "Towers of Doom", "Volskaya Foundry", "Warhead Junction"],
        "Mal'Ganis": ["Alterac Pass", "Battlefield of Eternity", "Braxis Holdout", "Hanamura Temple", "Infernal Shrines", "Sky Temple", "Towers of Doom"],
        "Medivh": ["Cursed Hollow", "Infernal Shrines"],
        "Muradin": ["Battlefield of Eternity", "Hanamura Temple"],
        "Stitches": ["Alterac Pass", "Cursed Hollow", "Tomb of the Spider Queen", "Towers of Doom", "Volskaya Foundry"],
        "Tyrael": ["Cursed Hollow", "Sky Temple", "Towers of Doom"],
        "Artanis": ["Garrosh", "Arthas", "Kael'thas", "Lunara", "Medivh", "Malfurion"],
        "Chen": ["Braxis Holdout", "Dragon Shire", "Hanamura Temple", "Infernal Shrines"],
        "D.Va": ["Infernal Shrines", "Tomb of the Spider Queen", "Towers of Doom", "Volskaya Foundry"],
        "Dehaka": ["Alterac Pass", "Braxis Holdout", "Cursed Hollow", "Dragon Shire", "Sky Temple", "Towers of Doom", "Warhead Junction"],
        "Imperius": ["Jaina", "Raynor", "Sgt. Hammer", "Zul'jin", "E.T.C.", "Yrel", "Blaze"],
        "Leoric": ["Cursed Hollow", "Garden of Terror", "Infernal Shrines", "Towers of Doom", "Volskaya Foundry"],
        "Malthael": ["Blackheart's Bay", "Dragon Shire", "Garden of Terror", "Infernal Shrines", "Sky Temple", "Tomb of the Spider Queen", "Towers of Doom", "Warhead Junction"],
        "Ragnaros": ["Blackheart's Bay", "Infernal Shrines", "Sky Temple", "Tomb of the Spider Queen", "Volskaya Foundry"],
        "Rexxar": ["Braxis Holdout", "Dragon Shire", "Tomb of the Spider Queen"],
        "Sonya": ["Blackheart's Bay", "Braxis Holdout", "Dragon Shire", "Garden of Terror", "Infernal Shrines"],
        "Thrall": ["Battlefield of Eternity", "Braxis Holdout", "Hanamura Temple", "Towers of Doom", "Volskaya Foundry"],
        "The Lost Vikings": ["Alterac Pass", "Cursed Hollow", "Garden of Terror", "Sky Temple", "Towers of Doom", "Warhead Junction", "Volskaya Foundry"],
        "Varian": ["Blackheart's Bay", "Braxis Holdout", "Dragon Shire", "Garden of Terror", "Hanamura Temple", "Towers of Doom", "Volskaya Foundry", "Warhead Junction"],
        "Xul": ["Blackheart's Bay", "Cursed Hollow", "Garden of Terror", "Infernal Shrines", "Sky Temple", "Tomb of the Spider Queen"],
        "Yrel": ["Braxis Holdout", "Dragon Shire", "Infernal Shrines", "Sky Temple", "Volskaya Foundry"],
        "Zarya": ["Battlefield of Eternity", "Braxis Holdout", "Hanamura Temple"],
        "Azmodan": ["Infernal Shrines", "Tomb of the Spider Queen", "Warhead Junction"],
        "Gazlowe": ["Alterac Pass", "Braxis Holdout", "Infernal Shrines", "Sky Temple", "Volskaya Foundry", "Warhead Junction"],
        "Hogger": ["Alterac Pass", "Blackheart's Bay", "Cursed Hollow", "Dragon Shire", "Garden of Terror", "Infernal Shrines", "Sky Temple"],
        "Mei": ["Braxis Holdout", "Cursed Hollow", "Hanamura Temple"],
        "Chromie": ["Volskaya Foundry", "Braxis Holdout"],
        "Falstad": ["Braxis Holdout", "Cursed Hollow", "Dragon Shire", "Hanamura Temple", "Towers of Doom", "Warhead Junction"],
        "Fenix": ["Braxis Holdout", "Infernal Shrines", "Tomb of the Spider Queen"],
        "Gall": ["Garden of Terror", "Infernal Shrines", "Tomb of the Spider Queen", "Volskaya Foundry"],
        "Genji": ["Cursed Hollow", "Hanamura Temple", "Garden of Terror", "Braxis Holdout"],
        "Greymane": ["Battlefield of Eternity", "Dragon Shire", "Garden of Terror", "Sky Temple", "Tomb of the Spider Queen"],
        "Gul'dan": ["Braxis Holdout", "Dragon Shire", "Infernal Shrines", "Sky Temple", "Tomb of the Spider Queen", "Volskaya Foundry", "Alterac Pass"],
        "Hanzo": ["Battlefield of Eternity", "Cursed Hollow", "Dragon Shire", "Infernal Shrines", "Towers of Doom", "Volskaya Foundry"],
        "Jaina": ["Braxis Holdout", "Dragon Shire", "Garden of Terror", "Infernal Shrines", "Tomb of the Spider Queen"],
        "Junkrat": ["Alterac Pass", "Braxis Holdout", "Cursed Hollow", "Dragon Shire", "Garden of Terror", "Infernal Shrines", "Sky Temple", "Tomb of the Spider Queen", "Towers of Doom", "Volskaya Foundry", "Warhead Junction"],
        "Kael'thas": ["Alterac Pass", "Braxis Holdout", "Dragon Shire", "Infernal Shrines", "Tomb of the Spider Queen", "Towers of Doom", "Volskaya Foundry"],
        "Kel'Thuzad": ["Battlefield of Eternity", "Braxis Holdout", "Towers of Doom"],
        "Li-Ming": ["Alterac Pass", "Battlefield of Eternity", "Cursed Hollow", "Infernal Shrines"],
        "Lunara": ["Battlefield of Eternity"],
        "Mephisto": ["Alterac Pass", "Battlefield of Eternity", "Braxis Holdout", "Infernal Shrines", "Volskaya Foundry"],
        "Nazeebo": ["Dragon Shire", "Tomb of the Spider Queen", "Volskaya Foundry"],
        "Nova": ["Dragon Shire", "Hanamura Temple", "Warhead Junction"],
        "Orphea": ["Anub'arak", "Chen", "Genji", "Johanna", "Lunara", "Muradin"],
        "Probius": ["Kerrigan", "Alarak", "Zeratul", "Tracer"],
        "Raynor": ["Johanna", "Artanis", "Cassia"],
        "Sgt. Hammer": ["Artanis", "Chromie", "Kel'Thuzad", "Li-Ming", "Stitches"],
        "Sylvanas": ["Alterac Pass", "Braxis Holdout", "Tomb of the Spider Queen", "Volskaya Foundry"],
        "Tassadar": ["Braxis Holdout", "Garden of Terror", "Infernal Shrines", "Tomb of the Spider Queen", "Volskaya Foundry"],
        "Tracer": ["Cursed Hollow", "Dragon Shire", "Sky Temple", "Towers of Doom", "Volskaya Foundry", "Warhead Junction"],
        "Tychus": ["Cursed Hollow", "Infernal Shrines", "Towers of Doom", "Volskaya Foundry"],
        "Valla": ["Battlefield of Eternity", "Infernal Shrines", "Tomb of the Spider Queen", "Volskaya Foundry"],
        "Zagara": ["Illidan", "Falstad", "Chen", "Zeratul"],
        "Zul'jin": ["E.T.C.", "Dehaka", "Diablo", "Garrosh", "Uther", "Li Li"],
        "Alarak": ["Battlefield of Eternity", "Towers of Doom"],
        "Illidan": ["Blackheart's Bay", "Cursed Hollow", "Garden of Terror", "Sky Temple", "Warhead Junction"],
        "Kerrigan": ["Alterac Pass", "Braxis Holdout", "Dragon Shire", "Infernal Shrines", "Tomb of the Spider Queen", "Volskaya Foundry"],
        "Maiev": ["Braxis Holdout", "Cursed Hollow", "Dragon Shire", "Garden of Terror", "Infernal Shrines", "Tomb of the Spider Queen"],
        "Murky": ["Garden of Terror"],
        "Qhira": ["Dragon Shire", "Hanamura Temple", "Tomb of the Spider Queen"],
        "Samuro": ["Alterac Pass", "Battlefield of Eternity", "Braxis Holdout", "Dragon Shire", "Sky Temple", "Towers of Doom"],
        "The Butcher": ["Dragon Shire", "Garden of Terror", "Sky Temple", "Tomb of the Spider Queen", "Towers of Doom", "Warhead Junction", "Volskaya Foundry"],
        "Valeera": ["Blackheart's Bay", "Cursed Hollow", "Dragon Shire", "Sky Temple", "Warhead Junction"],
        "Zeratul": ["Cursed Hollow", "Infernal Shrines", "Sky Temple", "Towers of Doom"],
        "Alexstrasza": ["Infernal Shrines"],
        "Ana": ["Hanamura Temple", "Tomb of the Spider Queen", "Towers of Doom"],
        "Anduin": ["Battlefield of Eternity", "Cursed Hollow", "Infernal Shrines", "Tomb of the Spider Queen"],
        "Auriel": ["Battlefield of Eternity", "Braxis Holdout", "Hanamura Temple"],
        "Brightwing": ["Alterac Pass", "Cursed Hollow", "Sky Temple", "Towers of Doom", "Warhead Junction"],
        "Deckard Cain": ["Alterac Pass", "Battlefield of Eternity", "Cursed Hollow", "Garden of Terror", "Infernal Shrines", "Volskaya Foundry"],
        "Kharazim": ["Braxis Holdout", "Dragon Shire", "Garden of Terror", "Infernal Shrines", "Sky Temple", "Towers of Doom", "Volskaya Foundry", "Warhead Junction"],
        "Li Li": ["Battlefield of Eternity", "Dragon Shire", "Hanamura Temple", "Volskaya Foundry"],
        "Lt. Morales": ["Battlefield of Eternity"],
        "Lúcio": ["Alterac Pass", "Hanamura Temple", "Cursed Hollow", "Battlefield of Eternity", "Towers of Doom"],
        "Malfurion": ["Alterac Pass", "Battlefield of Eternity", "Braxis Holdout", "Garden of Terror", "Infernal Shrines"],
        "Rehgar": ["Battlefield of Eternity", "Braxis Holdout", "Cursed Hollow", "Dragon Shire", "Infernal Shrines", "Sky Temple", "Tomb of the Spider Queen", "Towers of Doom", "Volskaya Foundry", "Warhead Junction"],
        "Stukov": ["Braxis Holdout", "Cursed Hollow"],
        "Tyrande": ["Battlefield of Eternity", "Dragon Shire", "Infernal Shrines", "Tomb of the Spider Queen"],
        "Uther": ["Infernal Shrines"],
        "Whitemane": ["Infernal Shrines", "Towers of Doom"]
    }
}; 