export const HERO_SLUGS = {
    'Abathur': 'abathur',
    'Alarak': 'alarak',
    'Alexstrasza': 'alexstrasza',
    'Ana': 'ana',
    'Anduin': 'anduin',
    'Anub\'arak': 'anubarak',
    'Arthas': 'arthas',
    'Artanis': 'artanis',
    'Auriel': 'auriel',
    'Azmodan': 'azmodan',
    'Blaze': 'blaze',
    'Brightwing': 'brightwing',
    'Cassia': 'cassia',
    'Chen': 'chen',
    'Cho': 'cho',
    'Chromie': 'chromie',
    'D.Va': 'dva',
    'Deathwing': 'deathwing',
    'Deckard Cain': 'deckard',
    'Dehaka': 'dehaka',
    'Diablo': 'diablo',
    'E.T.C.': 'etc',
    'Falstad': 'falstad',
    'Fenix': 'fenix',
    'Gall': 'gall',
    'Garrosh': 'garrosh',
    'Gazlowe': 'gazlowe',
    'Genji': 'genji',
    'Greymane': 'greymane',
    'Gul\'dan': 'guldan',
    'Hanzo': 'hanzo',
    'Hogger': 'hogger',
    'Illidan': 'illidan',
    'Imperius': 'imperius',
    'Jaina': 'jaina',
    'Johanna': 'johanna',
    'Junkrat': 'junkrat',
    'Kael\'thas': 'kaelthas',
    'Kel\'Thuzad': 'kel-thuzad',
    'Kerrigan': 'kerrigan',
    'Kharazim': 'kharazim',
    'Leoric': 'leoric',
    'Li Li': 'li-li',
    'Li-Ming': 'li-ming',
    'Lt. Morales': 'lt-morales',
    'Lúcio': 'lucio',
    'Lunara': 'lunara',
    'Maiev': 'maiev',
    'Mal\'Ganis': 'malganis',
    'Malfurion': 'malfurion',
    'Malthael': 'malthael',
    'Medivh': 'medivh',
    'Mei': 'mei',
    'Mephisto': 'mephisto',
    'Muradin': 'muradin',
    'Murky': 'murky',
    'Nazeebo': 'nazeebo',
    'Nova': 'nova',
    'Orphea': 'orphea',
    'Probius': 'probius',
    'Qhira': 'qhira',
    'Ragnaros': 'ragnaros',
    'Raynor': 'raynor',
    'Rehgar': 'rehgar',
    'Rexxar': 'rexxar',
    'Samuro': 'samuro',
    'Sgt. Hammer': 'sgt-hammer',
    'Sonya': 'sonya',
    'Stitches': 'stitches',
    'Stukov': 'stukov',
    'Sylvanas': 'sylvanas',
    'Tassadar': 'tassadar',
    'The Butcher': 'the-butcher',
    'The Lost Vikings': 'the-lost-vikings',
    'Thrall': 'thrall',
    'Tracer': 'tracer',
    'Tychus': 'tychus',
    'Tyrael': 'tyrael',
    'Tyrande': 'tyrande',
    'Uther': 'uther',
    'Valeera': 'valeera',
    'Valla': 'valla',
    'Varian': 'varian',
    'Whitemane': 'whitemane',
    'Xul': 'xul',
    'Yrel': 'yrel',
    'Zagara': 'zagara',
    'Zarya': 'zarya',
    'Zeratul': 'zeratul',
    'Zul\'jin': 'zuljin'
};

export function heroToSlug(hero) {
    if (HERO_SLUGS[hero]) {
        return HERO_SLUGS[hero];
    }
    return hero
        .toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '');
}
